// Создаем массив asideThemes с темами для блока aside
export const asideThemes = [
  'Skills C',
  'Skills C++',
  'Skills JS',
  'Vacancy',
  'Epam',
  'DSR',
  'Neoflex',
  'Yandex',
  'Ozon',
  'Avito',
  'Сбер',
  'Т Банк',
  'Иннотех',
  'Interview',
  'Postcross',
  'Приглашения',
  'Отказы',
  'Без ответа',
];
